import { Domain } from '@prisma/client';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import { Button } from '@/components/ui/button';
import Link from 'next/link';

interface DomainTableProps {
  domains: Domain[];
}

export default function DomainTable({ domains }: DomainTableProps) {
  return (
    <Table>
      <TableHeader>
        <TableRow>
          <TableHead>Domain Name</TableHead>
          <TableHead>Length</TableHead>
          <TableHead>TLD</TableHead>
          <TableHead>Categories</TableHead>
          <TableHead>Keywords</TableHead>
          <TableHead>Memorability</TableHead>
          <TableHead>Pronounceability</TableHead>
          <TableHead>Brandability</TableHead>
          <TableHead>Status</TableHead>
          <TableHead>Generated By</TableHead>
          <TableHead>Created At</TableHead>
          <TableHead>Description</TableHead>
          <TableHead>Actions</TableHead>
        </TableRow>
      </TableHeader>
      <TableBody>
        {domains.map((domain) => (
          <TableRow key={domain.id}>
            <TableCell>{domain.name}</TableCell>
            <TableCell>{domain.length}</TableCell>
            <TableCell>{domain.tld}</TableCell>
            <TableCell>{domain.possibleCategories.join(', ')}</TableCell>
            <TableCell>{domain.possibleKeywords.join(', ')}</TableCell>
            <TableCell>{domain.memorabilityScore.toFixed(2)}</TableCell>
            <TableCell>{domain.pronounceabilityScore.toFixed(2)}</TableCell>
            <TableCell>{domain.brandabilityScore.toFixed(2)}</TableCell>
            <TableCell>{domain.availabilityStatus}</TableCell>
            <TableCell>{domain.generatedByBot}</TableCell>
            <TableCell>{domain.createdAt.toLocaleDateString()}</TableCell>
            <TableCell>{domain.description}</TableCell>
            <TableCell>
              <div className="space-x-2">
                <Button asChild size="sm">
                  <Link href={`/domains/${domain.id}`}>View</Link>
                </Button>
                <Button size="sm" variant="outline">
                  Edit
                </Button>
                <Button size="sm" variant="destructive">
                  Delete
                </Button>
              </div>
            </TableCell>
          </TableRow>
        ))}
      </TableBody>
    </Table>
  );
}